Refine "GraphEditor" component, extend sample graphs
songofroland/pt-dijkstra pull request #9
Opened 2021-05-05 19:05 UTC by songofroland

2021-05-08 21:51 UTC, wilmhit requested changes

2021-05-08 21:51 UTC, wilmhit commented on src/App.css
> -.valid-base {
Is the text still centered?

2021-05-08 21:51 UTC, wilmhit commented on src/components/GraphEditor.tsx
> +  : { possibleValues: any[], selectCallback: Function , selectedLabel: string})
We were using `Array<any` notation up to this point so lets stick with that

2021-05-08 21:51 UTC, wilmhit commented on src/logic/graphSamples.ts
> +      [1,1,1,0],
If you're still using vim keybindings press == while in normal mode in this line.

2021-05-08 21:51 UTC, wilmhit commented on src/components/GraphEditor.tsx
> +  const [selectedGraphName, setSelectedGraphName] = useState('simple');
`Name` resembles more `label` field rather than `key` field

2021-05-11 07:55 UTC, songofroland commented on src/App.css
> -.valid-base {
It wasn't, good catch

2021-05-13 18:41 UTC, merged